server:
  port: 8080
  servlet:
    context-path: /bbs
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_bbs?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:com/bbs/mapper/*.xml
  type-aliases-package: com.bbs.entity
logging:
  level:
    root: info
    com.bbs: debug
